### ISSUE TITLE
Translate README to Chinese

### ISSUE THREAD

**Issue by nmdias** [nmdias/InfoKit#1]
Chinese is the #1 spoken language in the world and I'd love to have InfoKit be more inclusive, unfortunately I don't speak Chinese. If you know Chinese, and would like to help out, I'd be eternally grateful.

Pull Requests to the README.zh-CN.md are super welcome

Thank you 🙏

**Comment by shaobaili3** [comment]
Hey Nuno,
Thanks for you created this open source project.

I am a Swift iOS developer came from China. I have translated README.zh-CN.md and pull the  request #2 .

Thanks,
Shaobai Li

**Comment by nmdias** [comment]
Hi @shaobaili3,

What a great contribution, thank you so much 🙏
